# Copyright (c) 1996-99 The Regents of the University of California. All
# Rights Reserved. Permission to use, copy, modify, and distribute this
# software and its documentation without fee, and without a written
# agreement is hereby granted, provided that the above copyright notice
# and this paragraph appear in all copies.  This software program and
# documentation are copyrighted by The Regents of the University of
# California. The software program and documentation are supplied "AS
# IS", without any accompanying services from The Regents. The Regents
# does not warrant that the operation of the program will be
# uninterrupted or error-free. The end-user understands that the program
# was developed for research purposes and is advised not to rely
# exclusively on the program for any reason.  IN NO EVENT SHALL THE
# UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT,
# SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS,
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE. THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATIONS TO PROVIDE MAINTENANCE, SUPPORT,
# UPDATES, ENHANCEMENTS, OR MODIFICATIONS.

include ../Makefile.config

# gen is not used now that GEF does not need a preprocessor
GEN =

CLASSES = \
	ArrowHead.class \
	ArrowHeadComposite.class \
	ArrowHeadDiamond.class \
	ArrowHeadNone.class \
	ArrowHeadTriangle.class \
	ArrowHeadGreater.class \
	ArrowHeadHalfTriangle.class \
	ArrowHeadQualifier.class \
	Cmd.class \
	CmdAdjustGrid.class \
	CmdAdjustGuide.class \
	CmdAdjustPageBreaks.class \
	CmdAlign.class \
	CmdCreateNode.class \
	CmdCopy.class \
	CmdDelete.class \
	CmdDispose.class \
	CmdDistribute.class \
	CmdExit.class \
	CmdGroup.class \
	CmdInsertPoint.class \
	CmdNudge.class \
	CmdNull.class \
	CmdOpen.class \
	CmdOpenPGML.class \
	CmdOpenWindow.class \
	CmdPaste.class \
	CmdPrint.class \
	CmdRemovePoint.class \
	CmdReorder.class \
	CmdSave.class \
	CmdSavePGML.class \
	CmdScroll.class \
	CmdSelectAll.class \
	CmdSelectInvert.class \
	CmdSelectNext.class \
	CmdSequence.class \
	CmdSetMode.class \
	CmdShowProperties.class \
	CmdShowURL.class \
	CmdSpawn.class \
	CmdUngroup.class \
	CmdUseReshape.class \
	CmdUseResize.class \
	CmdUseRotate.class \
	Diagram.class \
	Editor.class \
	ExecuteCmdWindow.class \
	Fig.class \
	FigCircle.class \
	FigEdge.class \
	FigEdgeLine.class \
	FigEdgeLineDotted.class \
	FigEdgeRectiline.class \
	FigEdgePoly.class \
	FigGroup.class \
	FigImage.class \
	FigInk.class \
	FigLine.class \
	FigNode.class \
	FigPoly.class \
	FigRRect.class \
	FigRect.class \
	FigSpline.class \
	FigText.class \
	FigTextEditor.class \
	Geometry.class \
	Globals.class \
	Guide.class \
	GuideGrid.class \
	Handle.class \
	JGraph.class \
	JGraphFrame.class \
	Layer.class \
	LayerDiagram.class \
	LayerGrid.class \
	LayerManager.class \
	LayerPageBreaks.class \
	LayerPerspective.class \
	LayerPolar.class \
	Mode.class \
	ModeBroom.class \
	ModeCreate.class \
	ModeCreateEdge.class \
	ModeCreatePolyEdge.class \
	ModeCreateFigCircle.class \
	ModeCreateFigImage.class \
	ModeCreateFigInk.class \
	ModeCreateFigLine.class \
	ModeCreateFigPoly.class \
	ModeCreateFigRRect.class \
	ModeCreateFigRect.class \
	ModeCreateFigSpline.class \
	ModeCreateFigText.class \
	ModeManager.class \
	ModeModify.class \
	ModePlace.class \
	ModePopup.class \
	ModeSelect.class \
	NetEdge.class \
	NetList.class \
	NetNode.class \
	NetPort.class \
	NetPrimitive.class \
	PaletteFig.class \
	PathConv.class \
	PathConvPercent.class \
	PathConvPercentPlusConst.class \
	PGMLParserIBM.class \
	PredFigInRect.class \
	Prefs.class \
	PrefsEditor.class \
	RedrawManager.class \
	Selection.class \
	SelectionManager.class \
	SelectionMove.class \
	SelectionNoop.class \
	SelectionReshape.class \
	SelectionResize.class \
	SelectionRotate.class

all: $(GEN) $(CLASSES)

gen: $(GEN)

classes: $(CLASSES)


clean:
	$(RM) *.class $(GEN)

