# Copyright (c) 1995, 1996 Regents of the University of California.
# All rights reserved.
#
# This software was developed by the Arcadia project
# at the University of California, Irvine.
#
# Redistribution and use in source and binary forms are permitted
# provided that the above copyright notice and this paragraph are
# duplicated in all such forms and that any documentation,
# advertising materials, and other materials related to such
# distribution and use acknowledge that the software was developed
# by the University of California, Irvine.  The name of the
# University may not be used to endorse or promote products derived
# from this software without specific prior written permission.
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
# WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.

include ../Makefile.config

CLASSES = \
	Action.class \
	ActionAdjustGrid.class \
	ActionAdjustGuide.class \
	ActionAlign.class \
	ActionCreateNode.class \
	ActionDelete.class \
	ActionDispose.class \
	ActionEditNode.class \
	ActionGroup.class \
	ActionInsertPoint.class \
	ActionNudge.class \
	ActionNull.class \
	ActionOpenWindow.class \
	ActionPrint.class \
	ActionRemovePoint.class \
	ActionReorder.class \
	ActionScroll.class \
	ActionSequence.class \
	ActionSelectNext.class \
	ActionSelectAll.class \
	ActionSelectInvert.class \
	ActionSetAttr.class \
	ActionSetMode.class \
	ActionShowURL.class \
	ActionSpawn.class \
	ActionUngroup.class \
	ActionQuit.class \
	ActiveComponent.class \
	ActiveButton.class \
	ActiveChoice.class \
	ActiveList.class \
	ArrowHead.class \
	ArrowHeadTriangle.class \
	ArrowHeadNone.class \
	FigEdgeRectiline.class \
	FigEdgeLine.class \
	Editor.class \
	MenuManager.class \
	EditorFrame.class \
	ExecuteActionWindow.class \
	Fig.class \
	FigCircle.class \
	FigEdge.class \
	FigInk.class \
	FigImage.class \
	FigLine.class \
	FigGroup.class \
	FigPoly.class \
	FigRect.class \
	FigRRect.class \
	FigText.class \
	FigNode.class \
	ForwardingPanel.class \
	ForwardingFrame.class \
	ForwardingComponent.class \
	Geometry.class \
	Globals.class \
	Guide.class \
	GuideGrid.class \
	Handle.class \
	Layer.class \
	LayerManager.class \
	LayerDiagram.class \
	LayerGrid.class \
	LayerPageBreaks.class \
	LayerPerspective.class \
	LayerPolar.class \
	Mode.class \
	ModeCreate.class \
	ModeCreateArc.class \
	ModeCreateFigCircle.class \
	ModeCreateFigInk.class \
	ModeCreateFigImage.class \
	ModeCreateFigLine.class \
	ModeCreateFigPoly.class \
	ModeCreateFigRect.class \
	ModeCreateFigRRect.class \
	ModeCreateFigText.class \
	ModeExampleKeys.class \
	ModeModify.class \
	ModePlace.class \
	ModeSelect.class \
	ModeManager.class \
	NetEdge.class \
	NetList.class \
	NetNode.class \
	NetPort.class \
	NetPrimitive.class \
	Palette.class \
	PaletteAttr.class \
	PaletteCompound.class \
	PaletteDecorator.class \
	PaletteFig.class \
	PaletteSticky.class \
	PaletteTop.class \
	Prefs.class \
	PrefsEditor.class \
	PredFigInRect.class \
	RedrawManager.class \
	SelectionManager.class \
	Selection.class \
	SelectionResize.class \
	SelectionReshape.class \
	SelectionRotate.class \
	ActionSave.class \
	ActionLoad.class 

all: $(GEN) $(CLASSES)

gen: $(GEN)

classes: $(CLASSES)


#GEF.java: GEF.m4 ../Makefile.config
#Compat.java: Compat.m4 ../Makefile.config
#ActionLoad.java: ActionLoad.m4 ../Makefile.config
#ActionSave.java: ActionSave.m4 ../Makefile.config
#ActionPrint.java: ActionPrint.m4 ../Makefile.config


clean:
	$(RM) *.class $(GEN)

