#
# Default UNIX Makefile for Argo/UML
#
# Must specify the relative dir of this
# Makefile to $(TOP)
#
REL_DIR=uci/uml/visual
include Sources.list
include ../../../Makefile.config


archive: objdir
	$(COPY) *.class $(OUT_DIR)

