#JAVAC= j2c_javac
JAVAC= /opt/jdk-1.1.4/bin/javac
#JAVAC= /extra/jrobbins0/Java-WorkShop2.0/JWS/sparc-S2/bin/fastjavac  
#JAVAC= javac  

#JDK_VERSION= jdk102
JDK_VERSION= jdk11

JAVA= /opt/jdk-1.1.4/bin/java
JFLAGS=
JAVADOC= /opt/jdk-1.1.1/bin/javadoc

#JAVA= /home/jrobbins/local/java/bin/java
#JFLAGS=
#JAVADOC= /home/jrobbins/local/java/bin/j2c_javadoc

#JAVA= java
#JFLAGS= 
#JAVADOC= javadoc


WIDGETS=SYMANTEC
#WIDGETS=

MAKE= /usr/ccs/bin/make
M4= /usr/ccs/bin/m4
FIND= /usr/bin/find
RM= /bin/rm -f

CHECKOUT= co
CHECKED_OUT= grep ":.*strict" RCS/*

.SUFFIXES: .java .class .m4
.java.class: ; $(JAVAC) $(JFLAGS) $<
.m4.java: ; $(M4) -D$(JDK_VERSION) -D$(WIDGETS) $*.m4 > $*.java


