

JAVAC= /opt/jdk-1.1.5/bin/javac
#JAVAC= /extra/jrobbins0/Java-WorkShop2.0/JWS/sparc-S2/bin/fastjavac  
#JAVAC= javac

JFLAGS= -d /tmp/jr
JDK_VERSION= 115
WIDGETS=swing


MAKE= /usr/ccs/bin/make
M4= /usr/ccs/bin/m4
FIND= /usr/bin/find
RM= /bin/rm -f

.SUFFIXES: .java .class .m4
.java.class: ; $(JAVAC) $(JFLAGS) $<
.m4.java: ; $(M4) -D$(JDK_VERSION) -D$(WIDGETS) $*.m4 > $*.java


