// $Id$
// Copyright (c) 2003 The Regents of the University of California. All
// Rights Reserved. Permission to use, copy, modify, and distribute this
// software and its documentation without fee, and without a written
// agreement is hereby granted, provided that the above copyright notice
// and this paragraph appear in all copies.  This software program and
// documentation are copyrighted by The Regents of the University of
// California. The software program and documentation are supplied "AS
// IS", without any accompanying services from The Regents. The Regents
// does not warrant that the operation of the program will be
// uninterrupted or error-free. The end-user understands that the program
// was developed for research purposes and is advised not to rely
// exclusively on the program for any reason.  IN NO EVENT SHALL THE
// UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT,
// SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS,
// ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
// THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
// SUCH DAMAGE. THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY
// WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
// PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
// CALIFORNIA HAS NO OBLIGATIONS TO PROVIDE MAINTENANCE, SUPPORT,
// UPDATES, ENHANCEMENTS, OR MODIFICATIONS.

/*
 * Section.java
 *
 * Created on 24. Februar 2002, 15:30
 */

/**
 *
 *Reading and writing preserved sections from the code
 *
 */
package org.argouml.language.cpp.generator;

import java.util.*;
import java.io.*;
import org.argouml.uml.generator.AbstractSection;


public class Section extends AbstractSection {

    public static String generate(String id, String INDENT) {
        return (generateTop( id, INDENT ) + generateBottom( id, INDENT ));
    }
    /** Variant of generate( String id, String INDENT ) which allows
     * parted generation of Top and Bottom, so that GeneratorXX.java
     * can place an initial body within the both identifying lines
     */
    public static String generateTop(String id, String INDENT) {
        String s = INDENT + "// don't delete the following line as it's needed to preserve source code of this";
	s += " autogenerated element\n";
        s += INDENT + "// section " + id + " begin\n";
        return s;
    }
    /** Variant of generate( String id, String INDENT ) which allows
     * parted generation of Top and Bottom, so that GeneratorXX.java
     * can place an initial body within the both identifying lines
     */
    public static String generateBottom(String id, String INDENT) {
        String s = "";
        s += INDENT + "// section " + id + " end\n";
	s += INDENT + "// don't delete the previous line as it's needed to preserve source code of this";
	s += " autogenerated element\n";
        return s;
    }
}
