# Copyright (c) 1996-99 The Regents of the University of California. All
# Rights Reserved. Permission to use, copy, modify, and distribute this
# software and its documentation without fee, and without a written
# agreement is hereby granted, provided that the above copyright notice
# and this paragraph appear in all copies.  This software program and
# documentation are copyrighted by The Regents of the University of
# California. The software program and documentation are supplied "AS
# IS", without any accompanying services from The Regents. The Regents
# does not warrant that the operation of the program will be
# uninterrupted or error-free. The end-user understands that the program
# was developed for research purposes and is advised not to rely
# exclusively on the program for any reason.  IN NO EVENT SHALL THE
# UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT,
# SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS,
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE. THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATIONS TO PROVIDE MAINTENANCE, SUPPORT,
# UPDATES, ENHANCEMENTS, OR MODIFICATIONS.



include ../../Makefile.config

# gen is not used now
GEN = 

CLASSES = \
	ChildGenUML.class \
	ClAttributeCompartment.class \
	ClClassName.class \
	ClOperationCompartment.class \
	CrAlreadyRealizes.class \
	CrAssocNameConflict.class \
	CrAttrNameConflict.class \
	CrCircularAssocClass.class \
	CrCircularComposition.class \
	CrCircularInheritance.class \
	CrClassMustBeAbstract.class \
	CrConflictingComposites.class \
	CrConstructorNeeded.class \
	CrCrossNamespaceAssoc.class \
	CrDisambigClassName.class \
	CrDisambigStateName.class \
	CrDupParamName.class \
	CrDupRoleNames.class \
	CrEmptyPackage.class \
	CrFinalSubclassed.class \
	CrIllegalGeneralization.class \
	CrIllegalName.class \
	CrInterfaceAllPublic.class \
	CrInterfaceOperOnly.class \
	CrInvalidBranch.class \
	CrInvalidFork.class \
	CrInvalidInitial.class \
	CrInvalidJoin.class \
	CrMergeClasses.class \
	CrMissingAttrName.class \
	CrMissingClassName.class \
	CrMissingStateName.class \
	CrMultiComposite.class \
	CrMultipleAgg.class \
	CrMultipleInitialStates.class \
	CrNWayAgg.class \
	CrNameConflict.class \
	CrNameConflictAC.class \
	CrNameConfusion.class \
	CrNavFromInterface.class \
	CrNoAssociations.class \
	CrNoGuard.class \
	CrNoIncomingTransitions.class \
	CrNoInitialState.class \
	CrNoInstanceVariables.class \
	CrNoOperations.class \
	CrNoOutgoingTransitions.class \
	CrNoTransitions.class \
	CrNoTriggerOrGuard.class \
	CrNonAggDataType.class \
	CrOperNameConflict.class \
	CrOppEndConflict.class \
	CrOppEndVsAttr.class \
	CrParamTypeNotImported.class \
	CrReservedName.class \
	CrSignatureConflict.class \
	CrSubclassReference.class \
	CrTooManyAssoc.class \
	CrTooManyAttr.class \
	CrTooManyClasses.class \
	CrTooManyOper.class \
	CrTooManyStates.class \
	CrTooManyTransitions.class \
	CrUML.class \
	CrUnconventionalAttrName.class \
	CrUnconventionalClassName.class \
	CrUnconventionalOperName.class \
	CrUnconventionalPackageName.class \
	CrUnnavigableAssoc.class \
	CrUselessAbstract.class \
	CrUselessInterface.class \
	CrUtilityViolated.class \
	Init.class

all: $(GEN) $(CLASSES)

gen: $(GEN)

classes: $(CLASSES)

clean:
	$(RM) *.class $(GEN)

