# Copyright (c) 1996-98 The Regents of the University of California. All
# Rights Reserved. Permission to use, copy, modify, and distribute this
# software and its documentation for educational, research and non-profit
# purposes, without fee, and without a written agreement is hereby granted,
# provided that the above copyright notice and this paragraph appear in all
# copies. Permission to incorporate this software into commercial products may
# be obtained by contacting the University of California. David F. Redmiles
# Department of Information and Computer Science (ICS) University of
# California Irvine, California 92697-3425 Phone: 714-824-3823. This software
# program and documentation are copyrighted by The Regents of the University
# of California. The software program and documentation are supplied "as is",
# without any accompanying services from The Regents. The Regents do not
# warrant that the operation of the program will be uninterrupted or
# error-free. The end-user understands that the program was developed for
# research purposes and is advised not to rely exclusively on the program for
# any reason. IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY
# PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
# INCLUDING LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS
# DOCUMENTATION, EVEN IF THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE. THE UNIVERSITY OF CALIFORNIA SPECIFICALLY
# DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE
# SOFTWARE PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATIONS TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.



include ../../Makefile.config

# gen is not used now
GEN = 

CLASSES = \
	AboutBox.class \
	Actions.class \
	ActionCreatePseudostate.class \
	AddToDoItemDialog.class \
	ArgoFileFilter.class \
	ClassGenerationDiaglog.class \
	CriticBrowserDialog.class \
	DelayedChangeNotify.class \
	DelayedVetoableChangeListener.class \
	DesignIssuesDialog.class \
	DetailsPane.class \
	DismissToDoItemDialog.class \
	DisplayTextTree.class \
	DocumentationManager.class \
	EmailExpertDialog.class \
	EmptyProject.class \
	GoAssocToSource.class \
	GoAssocToTarget.class \
	GoClassToAggrClass.class \
	GoClassToAssocdClass.class \
	GoClassToCompositeClass.class \
	GoClassifierToBeh.class \
	GoClassifierToStr.class \
	GoDiagramToEdge.class \
	GoDiagramToNode.class \
	GoElementToMachine.class \
	GoFilteredChildren.class \
	GoGenElementToDerived.class \
	GoListToDecisionsToItems.class \
	GoListToGoalsToItems.class \
	GoListToPriorityToItem.class \
	GoMachineToStartState.class \
	GoMachineToState.class \
	GoMachineToTrans.class \
	GoModelToActor.class \
	GoModelToAssociation.class \
	GoModelToBaseElements.class \
	GoModelToClass.class \
	GoModelToDiagram.class \
	GoModelToElements.class \
	GoModelToUseCase.class \
	GoProjectDiagram.class \
	GoProjectModel.class \
	GoStateToIncomingTrans.class \
	GoStateToOutgoingTrans.class \
	GoStateToUpstream.class \
	GoStateToDownstream.class \
	GoStateToSubstate.class \
	GoTransToSourceState.class \
	GoTransToTargetState.class \
	GoalsDialog.class \
	JasonsTheme.class \
	JasonsBigTheme.class \
	JasonsHugeTheme.class \
	JavaDocument.class \
	JavaEditorKit.class \
	Menu.class \
	ModelElementRenderer.class \
	MultiEditorPane.class \
	NavigatorConfigDialog.class \
	NavPerspective.class \
	NavigatorPane.class \
	PredIsFinalState.class \
	PredIsStartState.class \
	PriorityNode.class \
	Project.class \
	ProjectBrowser.class \
	PropPanel.class \
	PropPanelAssoc.class \
	PropPanelAttr.class \
	PropPanelOper.class \
	PropPanelClass.class \
	PropPanelDiagram.class \
	PropPanelInterface.class \
	PropPanelModel.class \
	PropPanelActor.class \
	PropPanelUseCase.class \
	PropPanelNote.class \
	PropPanelState.class \
	PropPanelTransition.class \
	PropPanelPseudostate.class \
	PropPanelInstance.class \
	PropPanelLink.class \
	SpacerPanel.class \
	SplashScreen.class \
	StatusBar.class \
	TabChecklist.class \
	TabConstraints.class \
	TabDiagram.class \
	TabDocs.class \
	TabHash.class \
	TabHistory.class \
	TabJavaSrc.class \
	TabModelTarget.class \
	TabProps.class \
	TabSpawnable.class \
	TabSrc.class \
	TabTable.class \
	TabTaggedValues.class \
	TabText.class \
	TabToDo.class \
	TabToDoTarget.class \
	TabUMLDisplay.class \
	ToDoByDecision.class \
	ToDoByGoal.class \
	ToDoByOffender.class \
	ToDoByPoster.class \
	ToDoByPriority.class \
	ToDoByType.class \
	ToDoPane.class \
	ToDoPerspective.class \
	ToDoTreeRenderer.class \
	Token.class \
	Trash.class \
	TreeModelComposite.class \
	TreeModelPrereqs.class \
	UMLListCellRenderer.class \
	UMLTreeCellRenderer.class \
	WizStep.class \
	WizDescription.class 


all: $(GEN) $(CLASSES)

gen: $(GEN)

classes: $(CLASSES)

clean:
	$(RM) *.class $(GEN)

