# Copyright (c) 1996-98 The Regents of the University of California. All
# Rights Reserved. Permission to use, copy, modify, and distribute this
# software and its documentation for educational, research and non-profit
# purposes, without fee, and without a written agreement is hereby granted,
# provided that the above copyright notice and this paragraph appear in all
# copies. Permission to incorporate this software into commercial products may
# be obtained by contacting the University of California. David F. Redmiles
# Department of Information and Computer Science (ICS) University of
# California Irvine, California 92697-3425 Phone: 714-824-3823. This software
# program and documentation are copyrighted by The Regents of the University
# of California. The software program and documentation are supplied "as is",
# without any accompanying services from The Regents. The Regents do not
# warrant that the operation of the program will be uninterrupted or
# error-free. The end-user understands that the program was developed for
# research purposes and is advised not to rely exclusively on the program for
# any reason. IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY
# PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
# INCLUDING LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS
# DOCUMENTATION, EVEN IF THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE. THE UNIVERSITY OF CALIFORNIA SPECIFICALLY
# DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE
# SOFTWARE PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATIONS TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
# ENHANCEMENTS, OR MODIFICATIONS.



include ../../Makefile.config

# gen is not used now
GEN = 

CLASSES = \
	Actions.class \
	AddToDoItemDialog.class \
	DelayedChangeNotify.class \
	DelayedVetoableChangeListener.class \
	DesignIssuesDialog.class \
	DetailsPane.class \
	DismissToDoItemDialog.class \
	DisplayTextTree.class \
	DocumentationManager.class \
	EmailExpertDialog.class \
	GoClassifierToBeh.class \
	GoClassifierToStr.class \
	GoDiagramToEdge.class \
	GoDiagramToNode.class \
	GoGenElementToDerived.class \
	GoListToDecisionsToItems.class \
	GoListToGoalsToItems.class \
	GoListToPriorityToItem.class \
	GoModelToBaseElements.class \
	GoModelToDiagram.class \
	GoModelToElements.class \
	GoProjectDiagram.class \
	GoProjectModel.class \
	GoalsDialog.class \
	JasonsTheme.class \
	Menu.class \
	ModelElementRenderer.class \
	MultiEditorPane.class \
	NavAssociation.class \
	NavContainment.class \
	NavDiagramCentric.class \
	NavInheritance.class \
	NavPackageCentric.class \
	NavPerspective.class \
	NavStrictContainment.class \
	NavigatorPane.class \
	PriorityNode.class \
	Project.class \
	ProjectBrowser.class \
	PropPanel.class \
	PropPanelAssoc.class \
	PropPanelAttr.class \
	PropPanelClass.class \
	PropPanelInterface.class \
	PropPanelModel.class \
	PropPanelOper.class \
	PseudoNodes.class \
	SpacerPanel.class \
	StatusBar.class \
	TabDiagram.class \
	TabDocs.class \
	TabHash.class \
	TabHistory.class \
	TabModelTarget.class \
	TabProps.class \
	TabSpawnable.class \
	TabSrc.class \
	TabTable.class \
	TabText.class \
	TabToDo.class \
	TabToDoTarget.class \
	TabUMLDisplay.class \
	ToDoByDecision.class \
	ToDoByGoal.class \
	ToDoByOffender.class \
	ToDoByPoster.class \
	ToDoByPriority.class \
	ToDoByType.class \
	ToDoPane.class \
	ToDoPerspective.class \
	ToDoTreeRenderer.class \
	Trash.class \
	TreeModelComposite.class \
	TreeModelPrereqs.class \
	UMLTreeCellRenderer.class


all: $(GEN) $(CLASSES)

gen: $(GEN)

classes: $(CLASSES)

clean:
	$(RM) *.class $(GEN)

