// Test suite automatically generated by Eclipse
// Update using "Recreate Test Suite..." from context menu in Eclipse
// NOTE: Mock tests are not compatible with suite

package org.argouml.model;

import junit.framework.Test;
import junit.framework.TestSuite;

public class AllTests {

    public static Test suite() {
        TestSuite suite = new TestSuite("Test for org.argouml.model");
        //$JUnit-BEGIN$
        suite.addTestSuite(TestModelFacade2.class);
        suite.addTestSuite(TestDataTypesFactory.class);
        suite.addTestSuite(TestCommonBehaviorHelper.class);
        suite.addTestSuite(TestUmlFactoryBuildNode.class);
        suite.addTestSuite(TestUmlExtend.class);
        suite.addTest(TestModel.suite());
        suite.addTestSuite(TestModelManagementHelper.class);
        suite.addTestSuite(TestCommonBehaviorFactory.class);
        suite.addTestSuite(TestCoreHelper.class);
        suite.addTestSuite(TestUseCasesHelper.class);
        suite.addTestSuite(TestModelEventPump.class);
        suite.addTestSuite(TestExtensionMechanismsFactory.class);
        suite.addTestSuite(TestUml.class);
        suite.addTestSuite(TestModelManagementFactory.class);
        suite.addTestSuite(TestUmlModel.class);
        suite.addTestSuite(TestUmlFactory.class);
        suite.addTestSuite(TestUmlActor.class);
        suite.addTest(TestAgainstUmlModel.suite());
        suite.addTestSuite(TestModel2.class);
        suite.addTestSuite(TestUmlUseCase.class);
        suite.addTestSuite(TestActivityGraphsHelper.class);
//        suite.addTestSuite(TestCoreHelperWithMock.class);
        suite.addTestSuite(TestUseCasesFactory.class);
        suite.addTestSuite(TestCoreFactory.class);
        suite.addTest(TestModelFacade3.suite());
//        suite.addTestSuite(TestAGHelperWithMock.class);
        suite.addTestSuite(TestCollaborationsHelper.class);
        suite.addTestSuite(TestUmlModelElement.class);
        suite.addTestSuite(TestExtensionMechanismsHelper.class);
        suite.addTestSuite(TestUmlGeneralization.class);
        suite.addTestSuite(TestCopyHelper.class);
        suite.addTestSuite(TestCollaborationsFactory.class);
        suite.addTestSuite(TestStateMachinesFactory.class);
        suite.addTestSuite(TestActivityGraphsFactory.class);
        suite.addTestSuite(TestStateMachinesHelper.class);
        //$JUnit-END$
        return suite;
    }

}
