# Copyright (c) 1996-99 The Regents of the University of California. All
# Rights Reserved. Permission to use, copy, modify, and distribute this
# software and its documentation without fee, and without a written
# agreement is hereby granted, provided that the above copyright notice
# and this paragraph appear in all copies.  This software program and
# documentation are copyrighted by The Regents of the University of
# California. The software program and documentation are supplied "AS
# IS", without any accompanying services from The Regents. The Regents
# does not warrant that the operation of the program will be
# uninterrupted or error-free. The end-user understands that the program
# was developed for research purposes and is advised not to rely
# exclusively on the program for any reason.  IN NO EVENT SHALL THE
# UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT,
# SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS,
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE. THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# CALIFORNIA HAS NO OBLIGATIONS TO PROVIDE MAINTENANCE, SUPPORT,
# UPDATES, ENHANCEMENTS, OR MODIFICATIONS.

#############################################
# Argo/UML Makefile config file developed for
# a Unix system.
#
# Author: Scott A. Guyer (sguyer@cs.vt.edu)
# Date: 03/06/1999
#############################################
#
# Make sure each of the following
# macros are define correctly.
#

# Top level directory for source distribution
ARGO_DIR=$(HOME)/cvs/argouml/src


# Path to JDK 1.1 or JDK 1.2 or equivalent
JAVA_DIR=/usr/lib/jdk1.2.2

#JAVA_DIR=/usr/remote/jdk12

#JAVAC=$(JAVA_DIR)/bin/javac
JAVA_AR=$(JAVA_DIR)/bin/jar
JAVADOC=$(JAVA_DIR)/bin/javadoc

# Path to JDK 1.2 JRE libraries or equivalent
JRE_DIR=$(JAVA_DIR)/jre

# if you have jikes (from www.alphaworks.ibm.com)
JAVAC=jikes 

# Java 1.1 classes
#JAVA_LIB=$(JAVA_DIR)/lib/classes.zip

# Java 1.2 classes
JAVA_LIB=$(JAVA_DIR)/lib/tools.jar:$(JAVA_DIR)/jre/lib/rt.jar

#JAVA_LIB=$(JRE_DIR)/lib/rt.jar

# Swing classes   (get from java.sun.com/products/jfc)
#SWING_LIB=/usr/lib/java/lib/swing.jar

# XML classes  (get from www.alphaworks.ibm.com)
# (this is in NSUML library path now)
# XML_LIB=$(ARGO_DIR)/xml4j.jar

# Novosofts nsuml library
NSUML_DIR=$(HOME)/Diplomarbeit/novosoft/nsuml
NSUML_LIB=$(NSUML_DIR)/lib/nsuml.jar:$(NSUML_DIR)/lib/collections.jar:$(NSUML_DIR)/lib/xml4j.jar
##############
# The way this works is that each makefile
# in every subdirectory must define REL_DIR
# to be the relative path from the top-level
# ARGO_DIR.
#
OBJ_DIR=$(ARGO_DIR)/archive

# Don't change these two
TOP=$(ARGO_DIR)/$(REL_DIR)
OUT_DIR=$(OBJ_DIR)/$(REL_DIR)



#########################################
# Some platform specific command macros #
#########################################
DELETE=rm -f
COPY=cp
MKDIR=mkdir -p
MAKE=make -f Makefile
CD=cd



#########################
#  DO NOT EDIT BELOW    #
#########################
CLASSPATH=$(JAVA_LIB):$(ARGO_DIR):$(SWING_LIB):$(NSUML_LIB)

JFLAGS= -classpath $(CLASSPATH)

# If you use jikes with emacs
#JFLAGS= +E -classpath $(CLASSPATH)

.SUFFIXES: .java .class

.java.class:
	$(JAVAC) $(JFLAGS) $<


classes: $(SOURCES:.java=.class)

objdir:
	if [ ! -d $(OUT_DIR) ] ; \
	then $(MKDIR) $(OUT_DIR) ; fi

all: classes archive

clean:
	$(DELETE) *.class
